// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `GetHistorial.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface _GetHistorialOperationsNC
{
    boolean comprobarUsuario(String usuario, String contrasena);

    String[] getProx(String usuario, String contrasena);

    String[] getTemp(String usuario, String contrasena);
}
